GET http://localhost:3000/payment HTTP/1.1



#### 

POST http://localhost:3000/payment HTTP/1.1
Content-Type: application/json

{
  "userId": "",
  "courseId": "",
  "amount": "",
  "mode": "",
  "status": "",
  "card": ""
    
}

